"""Hebrew parsha name (from hdate) -> English name. Synced with app.py / agents tooling."""

PARSHA_MAP = {
    "בראשית": "Bereishit",
    "נח": "Noach",
    "לך לך": "Lech Lecha",
    "וירא": "Vayera",
    "חיי שרה": "Chayei Sarah",
    "תולדות": "Toldot",
    "ויצא": "Vayetzei",
    "וישלח": "Vayishlach",
    "וישב": "Vayeshev",
    "מקץ": "Miketz",
    "ויגש": "Vayigash",
    "ויחי": "Vayechi",
    "שמות": "Shemot",
    "וארא": "Vaera",
    "בא": "Bo",
    "בשלח": "Beshalach",
    "יתרו": "Yitro",
    "משפטים": "Mishpatim",
    "תרומה": "Terumah",
    "תצוה": "Tetzaveh",
    "כי תשא": "Ki Tisa",
    "ויקהל": "Vayakhel",
    "פקודי": "Pekudei",
    "ויקרא": "Vayikra",
    "צו": "Tzav",
    "שמיני": "Shemini",
    "תזריע": "Tazria",
    "מצורע": "Metzora",
    "אחרי מות": "Acharei Mot",
    "קדושים": "Kedoshim",
    "אמור": "Emor",
    "בהר": "Behar",
    "בחוקותי": "Bechukotai",
    "במדבר": "Bamidbar",
    "נשא": "Naso",
    "בהעלותך": "Beha'alotcha",
    "שלח": "Shelach",
    "קרח": "Korach",
    "חקת": "Chukat",
    "בלק": "Balak",
    "פינחס": "Pinchas",
    "מטות": "Matot",
    "מסעי": "Masei",
    "דברים": "Devarim",
    "ואתחנן": "Vaetchanan",
    "עקב": "Eikev",
    "ראה": "Re'eh",
    "שופטים": "Shoftim",
    "כי תצא": "Ki Teitzei",
    "כי תבוא": "Ki Tavo",
    "נצבים": "Nitzavim",
    "וילך": "Vayeilech",
    "האזינו": "Haazinu",
    "וזאת הברכה": "Vezot Habracha",
}
